import React, { useMemo } from 'react';
import DOMPurify from 'dompurify';

interface HtmlRendererProps {
  content: string;
  className?: string;
  style?: React.CSSProperties;
}

const isHtml = (str: string) => {
  const doc = new DOMParser().parseFromString(str, 'text/html');
  return Array.from(doc.body.childNodes).some(node => node.nodeType === 1);
};

export const HtmlRenderer: React.FC<HtmlRendererProps> = ({ content, className, style }) => {
  const sanitizedHtml = useMemo(() => {
    if (!content) return '';

    let htmlToSanitize = content;
    
    // Clean up any trailing empty paragraphs that might have been generated by the rich text editor
    // This prevents large empty spaces at the bottom of the rendered description.
    htmlToSanitize = htmlToSanitize.replace(/(<p>\s*(?:<br>)?\s*<\/p>|\s)+$/i, '');
    
    // If it's plain text (legacy description), wrap in <p> and convert newlines to <br>
    if (!isHtml(htmlToSanitize)) {
      htmlToSanitize = `<p>${htmlToSanitize.replace(/\n/g, '<br>')}</p>`;
    }

    // Sanitize with DOMPurify
    return DOMPurify.sanitize(htmlToSanitize, {
      ALLOWED_TAGS: ['p', 'br', 'strong', 'em', 'u', 'ul', 'ol', 'li', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'span'],
      ALLOWED_ATTR: ['style', 'class'],
    });
  }, [content]);

  return (
    <div 
      className={`html-renderer ${className || ''}`}
      style={{ ...style, wordBreak: 'break-word', whiteSpace: 'normal' }}
      dangerouslySetInnerHTML={{ __html: sanitizedHtml }} 
    />
  );
};

export default HtmlRenderer;
